services:
  api:
    image: ghcr.io/ministryofjustice/hmpps-sentence-plan:local
    build:
      target: development
    command: gradle --parallel --build-cache --configuration-cache bootRun
    ports:
      - "5005:5005"
    volumes:
      - ..:/app
      - ~/.gradle:/home/gradle/.gradle
