services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sentence-plan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hmpps-auth:9090/auth/health"]
    environment:
      SERVER_PORT: 9090
      SPRING_PROFILES_ACTIVE: dev
      APPLICATION_AUTHENTICATION_UI_ALLOWLIST: 0.0.0.0/0
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG

  hmpps-auth-proxy:
    image: nginx:latest
    depends_on:
      - hmpps-auth
    volumes:
      - ./hmpps-auth-proxy/nginx.conf:/etc/nginx/nginx.conf

  wiremock:
    build:
      context: wiremock
    volumes:
      - ./wiremock/mocks:/home/wiremock

  api:
    image: quay.io/hmpps/hmpps-sentence-plan:${APP_VERSION:-latest}
    build:
      context: ../
    depends_on:
      - postgres
      - hmpps-auth
      - wiremock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:8080/health/ping"]
      interval: 5s
      retries: 100
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DB_ENDPOINT: postgres:5432
      ARNS_API_CLIENT_ID: sentence-plan-api-client
      ARNS_API_CLIENT_SECRET: clientsecret
      HMPPS_AUTH_BASE_URL: http://hmpps-auth:9090
      ARNS_API_BASE_URL: http://wiremock:8080/arns-api
      DELIUS_API_BASE_URL: http://wiremock:8080/delius-api