services:
  postgres:
    ports:
      - "5432:5432"

  hmpps-auth:
    ports:
      - "9090:9090"

  forward-proxy:
    ports:
      - "9091:9091"

  api:
    image: quay.io/hmpps/hmpps-sentence-plan:local
    build:
      target: development
    command: gradle --parallel --build-cache --configuration-cache bootRun
    ports:
      - "5005:5005"
    volumes:
      - ..:/app
      - ~/.gradle:/home/gradle/.gradle
