events {
}
http {
  server {
    listen 9091;
    location / {
      proxy_pass http://hmpps-auth:9090;
    }
  }

  server {
    listen 9092;
    location / {
      add_header Content-Type text/plain;
      return 200 'Feedback';
    }
  }
}
