---
# Per environment values which override defaults in hmpps-sentence-plan/values.yaml

generic-service:
  ingress:
    host: hmpps-sentence-plan.hmpps.service.justice.gov.uk


  env:
    SPRING_PROFILES_ACTIVE: "prod"
    HMPPS_AUTH_BASE_URL: https://sign-in-prod.hmpps.service.justice.gov.uk
    ARNS_API_BASE_URL: https://assess-risks-and-needs-prod.hmpps.service.justice.gov.uk
    DELIUS_API_BASE_URL: https://sentence-plan-and-delius-prod.hmpps.service.justice.gov.uk
    USE_STUB: false

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-sentence-plan-notifications

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: [ "ALL" ]
