---
# Per environment values which override defaults in hmpps-sentence-plan/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-sentence-plan-preprod.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: "preprod"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_BASE_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-sentence-plan-notifications
