CREATE TABLE steps (
                       id SERIAL PRIMARY KEY,
                       name VARCHAR NOT NULL,
                       goal_id INT NOT NULL,
                       active boolean NOT NULL,
                       CONSTRAINT fk_goal
                           FOREIGN KEY(goal_id)
                               REFERENCES goals(id)
);


insert into steps(name, goal_id, active) values ('Improve relationship with neighbours - Step A', 1, '1');
insert into steps(name, goal_id, active) values ('Improve relationship with neighbours - Step B', 1, '1');
insert into steps(name, goal_id, active) values ('Improve relationship with neighbours - Step C', 1, '1');
insert into steps(name, goal_id, active) values ('Improve relationship with neighbours - Step D', 1, '1');
insert into steps(name, goal_id, active) values ('Improve relationship with neighbours - Step E', 1, '1');
insert into steps(name, goal_id, active) values ('Improve relationship with neighbours - Step F', 1, '1');
insert into steps(name, goal_id, active) values ('Find suitable accommodation - Step A', 2, '1');
insert into steps(name, goal_id, active) values ('Find suitable accommodation - Step B', 2, '1');
insert into steps(name, goal_id, active) values ('Find suitable accommodation - Step C', 2, '1');
insert into steps(name, goal_id, active) values ('Find suitable accommodation - Step D', 2, '1');
insert into steps(name, goal_id, active) values ('Find suitable accommodation - Step E', 2, '1');
insert into steps(name, goal_id, active) values ('Find suitable accommodation - Step F', 2, '1');
insert into steps(name, goal_id, active) values ('Find suitable accommodation - Step G', 2, '1');
insert into steps(name, goal_id, active) values ('Find suitable accommodation - Step H', 2, '1');
insert into steps(name, goal_id, active) values ('Find suitable accommodation - Step J', 2, '1');
insert into steps(name, goal_id, active) values ('Find suitable accommodation - Step K', 2, '1');
insert into steps(name, goal_id, active) values ('Reduce risk of eviction - Step A', 3, '1');
insert into steps(name, goal_id, active) values ('Reduce risk of eviction - Step B', 3, '1');
insert into steps(name, goal_id, active) values ('Reduce risk of eviction - Step C', 3, '1');
insert into steps(name, goal_id, active) values ('Reduce risk of eviction - Step D', 3, '1');
insert into steps(name, goal_id, active) values ('Reduce risk of eviction - Step E', 3, '1');
insert into steps(name, goal_id, active) values ('Follow rules of  accommodation provider  - Step A', 4, '1');
insert into steps(name, goal_id, active) values ('Follow rules of  accommodation provider  - Step B', 4, '1');
insert into steps(name, goal_id, active) values ('Follow rules of  accommodation provider  - Step C', 4, '1');
insert into steps(name, goal_id, active) values ('Follow rules of  accommodation provider  - Step D', 4, '1');
insert into steps(name, goal_id, active) values ('Follow rules of  accommodation provider  - Step E', 4, '1');
insert into steps(name, goal_id, active) values ('Follow rules of  accommodation provider  - Step F', 4, '1');
insert into steps(name, goal_id, active) values ('Follow rules of  accommodation provider  - Step G', 4, '1');
insert into steps(name, goal_id, active) values ('Follow rules of  accommodation provider  - Step H', 4, '1');
insert into steps(name, goal_id, active) values ('Have housing needs assessed - Step A', 5, '1');
insert into steps(name, goal_id, active) values ('Have housing needs assessed - Step B', 5, '1');
insert into steps(name, goal_id, active) values ('Have housing needs assessed - Step C', 5, '1');
insert into steps(name, goal_id, active) values ('Have housing needs assessed - Step D', 5, '1');
insert into steps(name, goal_id, active) values ('Have housing needs assessed - Step E', 5, '1');
insert into steps(name, goal_id, active) values ('Have housing needs assessed - Step F', 5, '1');
insert into steps(name, goal_id, active) values ('Have housing needs assessed - Step G', 5, '1');
insert into steps(name, goal_id, active) values ('Have housing needs assessed - Step H', 5, '1');
insert into steps(name, goal_id, active) values ('Have housing needs assessed - Step J', 5, '1');
insert into steps(name, goal_id, active) values ('Have housing needs assessed - Step K', 5, '1');
insert into steps(name, goal_id, active) values ('Have housing needs assessed - Step L', 5, '1');
insert into steps(name, goal_id, active) values ('Reduce or pay off any unpaid rent - Step A', 6, '1');
insert into steps(name, goal_id, active) values ('Reduce or pay off any unpaid rent - Step B', 6, '1');
insert into steps(name, goal_id, active) values ('Reduce or pay off any unpaid rent - Step C', 6, '1');
insert into steps(name, goal_id, active) values ('Reduce or pay off any unpaid rent - Step D', 6, '1');
insert into steps(name, goal_id, active) values ('Reduce or pay off any unpaid rent - Step E', 6, '1');
insert into steps(name, goal_id, active) values ('Reduce or pay off any unpaid rent - Step F', 6, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step A', 7, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step B', 7, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step C', 7, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step D', 7, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step E', 7, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step F', 7, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step G', 7, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step H', 7, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step J', 7, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step K', 7, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step L', 7, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step M', 7, '1');
insert into steps(name, goal_id, active) values ('Actively try to find suitable housing - Step N', 7, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 1 - Step A', 8, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 1 - Step B', 8, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 1 - Step C', 8, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 1 - Step D', 8, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 1 - Step E', 8, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 2 - Step A', 9, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 2 - Step B', 9, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 2 - Step C', 9, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 2 - Step D', 9, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 2 - Step E', 9, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 2 - Step F', 9, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 2 - Step G', 9, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 3 - Step A', 10, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 3 - Step B', 10, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 3 - Step C', 10, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 3 - Step D', 10, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 3 - Step E', 10, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 3 - Step F', 10, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 4 - Step A', 11, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 4 - Step B', 11, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 4 - Step C', 11, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 4 - Step D', 11, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 4 - Step E', 11, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 4 - Step F', 11, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 4 - Step G', 11, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 4 - Step H', 11, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 5 - Step A', 12, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 5 - Step B', 12, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 5 - Step C', 12, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step A', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step B', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step C', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step D', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step E', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step F', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step G', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step H', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step J', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step K', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step L', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step M', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 6 - Step N', 13, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 7 - Step A', 14, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 7 - Step B', 14, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 7 - Step C', 14, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 7 - Step D', 14, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 7 - Step E', 14, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 8 - Step A', 15, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 8 - Step B', 15, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 8 - Step C', 15, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 8 - Step D', 15, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 9 - Step A', 16, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 9 - Step B', 16, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 9 - Step C', 16, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 9 - Step D', 16, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 9 - Step E', 16, '1');
insert into steps(name, goal_id, active) values ('Drugs Goal 9 - Step F', 16, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 1 - Step A', 17, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 1 - Step B', 17, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 1 - Step C', 17, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 1 - Step D', 17, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 1 - Step E', 17, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 1 - Step F', 17, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 2 - Step A', 18, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 2 - Step B', 18, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 2 - Step C', 18, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 2 - Step D', 18, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 2 - Step E', 18, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 2 - Step F', 18, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 2 - Step G', 18, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 2 - Step H', 18, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 3 - Step A', 19, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 3 - Step B', 19, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 3 - Step C', 19, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 3 - Step D', 19, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 4 - Step A', 20, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 4 - Step B', 20, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 4 - Step C', 20, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 4 - Step D', 20, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 4 - Step E', 20, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 4 - Step F', 20, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 4 - Step G', 20, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 4 - Step H', 20, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 5 - Step A', 21, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 5 - Step B', 21, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 5 - Step C', 21, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 5 - Step D', 21, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 6 - Step A', 22, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 6 - Step B', 22, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 6 - Step C', 22, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 7 - Step A', 23, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 7 - Step B', 23, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 7 - Step C', 23, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 7 - Step D', 23, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 7 - Step E', 23, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 7 - Step F', 23, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 7 - Step G', 23, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 7 - Step H', 23, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 7 - Step J', 23, '1');
insert into steps(name, goal_id, active) values ('Health and Wellbeing Goal 7 - Step K', 23, '1');