name: Build and test PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm_lint:
    name: Helm lint
    strategy:
      matrix:
        environments: ['dev', 'test', 'preprod', 'prod']
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2
    secrets: inherit
    with:
      environment: ${{ matrix.environments }}

  validate:
    uses: ./.github/workflows/validate.yml